#!/bin/zsh -f

eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="$HOME/.config/emacs/bin:$HOME/code/gitstack:$PATH"
export COLIMA_SAVE_CONFIG=0

# rust
if [[ -f "$HOME/.cargo/env" ]]; then
  . "$HOME/.cargo/env"
fi
