import = [
    "~/.config/alacritty/active_theme.toml"
]

[env]
term = "xterm-256color"

[font]
size = 16

[font.bold]
family = "Mononoki Nerd Font Propo"

[font.italic]
family = "Mononoki Nerd Font Propo"

[font.normal]
family = "Mononoki Nerd Font Propo"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
decorations = "None"

# # colors come from the "Aura" theme
# [colors.primary]
# background = "#15141b"
# foreground = "#edecee"

# [colors.cursor]
# cursor = "#a277ff"

# [colors.selection]
# text = "CellForeground"
# background = "#29263c"

# [colors.normal]
# black = "#110f18"
# red = "#ff6767"
# green = "#61ffca"
# yellow = "#ffca85"
# blue = "#a277ff"
# magenta = "#a277ff"
# cyan = "#00ffff"  # cyan was the same as green in the original
# white = "#edecee"

# [colors.bright]
# black = "#4d4d4d"
# red = "#ff6767"
# green = "#61ffca"
# yellow = "#ffca85"
# blue = "#a277ff"
# magenta = "#a277ff"
# cyan = "#61ffca"
# white = "#edecee"
