tap "homebrew/cask-fonts"
tap "macos-fuse-t/homebrew-cask"

brew "android-platform-tools"
brew "aspell"
brew "colima"
brew "coreutils"
brew "derailed/k9s/k9s"
brew "docker"
brew "ffmpeg"
brew "fuse-t"
brew "fzf"
brew "gh"
brew "go"
brew "graphviz"
brew "imagemagick"
brew "k9s"
brew "pdsh"
brew "reattach-to-user-namespace"
brew "terraform"
brew "tmux"
brew "yq"
brew "zsh-syntax-highlighting"

cask "cryptomator"
cask "font-source-code-pro-for-powerline"
cask "google-drive"
cask "mactex"
