tap "homebrew/cask-fonts"

brew "aspell"
brew "colima"
brew "coreutils"
brew "derailed/k9s/k9s"
brew "docker"
brew "fzf"
brew "gh"
brew "graphviz"
brew "pdsh"
brew "reattach-to-user-namespace"
brew "tmux"
brew "yq"
brew "zsh-syntax-highlighting"

cask "font-source-code-pro-for-powerline"
