wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    gcal:
      colors:
        title: "white"
        eventTime: "lightblue"
        description: "yellow"
        past: "darkgrey"
        highlights:
          - ['1:1', 'green']
          - [' / ', 'green']
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "EMAIL"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: true
      position:
        top: 0
        left: 0
        height: 4
        width: 2
      refreshInterval: 5m
      # secret file from https://developers.google.com/calendar/api/quickstart/go
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      showDeclined: true
      showEndTime: false
      timezone: "America/Los_Angeles"
      withLocation: true
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 2
        height: 4
        width: 2
      refreshInterval: 1h
    jira:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://COMPANY.atlassian.net"
      email: "EMAIL"
      enabled: true
      jql: "issuetype = Task AND status NOT IN (\"Closed\", \"Done\", \"Won't Do\")"
      position:
        top: 4
        left: 0
        height: 4
        width: 4
      project: ""
      refreshInterval: 15m
      username: "EMAIL"
      verifyServerCertificate: true
